---
title: "422_Programming_Assignment_01"
author: "Michael Gilbert"
date: "March 28, 2016"
output: github_document
---
\
```{r setup, include = F}
# Backslash above adds an extra line before next paragraph begins.
# Option include = F means {knitr} will run the chunk, but not include it in
#   the final document.
# Default value (echo = T) - {knitr} will display the code in the chunk above
#   its results in the final document.
knitr::opts_chunk$set(echo = T)
```

## ISLR, Section 2.4
### Exercise 8:

This exercise relates to the `College` data set, which can be found in the file `College.csv`. It contains a number of variables for the 777 different universities and colleges in the US. *[Note: variable list excluded]*

(a) Use the `read.csv()` function to read the data into `R`. Call the loaded data `college`. Make sure that you have the directory set to the correct  location for the data.



(b) Look at the data using the `fix()` function. You should notice that the first column is just the name of each university.We don't really want `R` to  treat this as data. However, it may be handy to have these names for later. Try the following commands:
\
\
`> rownames (college )=college [,1]`
\
`> fix (college )`
\
\
You should see that there is now a `row.names` column with the name of each university recorded. This means that `R` has given each row a name corresponding to the appropriate university. `R` will not try to perform calculations on the row names. However, we still need to eliminate the first column in the data where the names are stored. Try:
\
\
`> college =college [,-1]`
\
`> fix (college )`
\
\
Now you should see that the first data column is `Private`. Note that another column labeled `row.names` now appears before the `Private` column. However, this is not a data column but rather the name that `R` is giving to each row.



(c) i. Use the `summary()` function to produce a numerical summary of the variables in the data set.



    ii. Use the `pairs()` function to produce a scatterplot matrix of the first ten columns or variables of the data. Recall that you can reference the     first ten columns of a matrix `A` using `A[,1:10]`.



    iii. Use the `plot()` function to produce side-by-side boxplots of `Outstate` versus `Private`.



    iv. Create a new qualitative variable, called `Elite`, by _binning_ the `Top10perc` variable. We are going to divide universities into two groups based on whether or not the proportion of students coming from the top 10% of their high school classes exceeds 50%.
\
\
`> Elite =rep ("No",nrow(college ))`
\
`> Elite [college$Top10perc >50]=" Yes"`
\
`> Elite =as.factor (Elite)`
\
`> college =data.frame(college ,Elite)`
\
\
Use the `summary()` function to see how many elite universities there are. Now use the `plot()` function to produce side-by-side boxplots of `Outstate` versus `Elite`.



    v. Use the `hist()` function to produce some histograms with differing numbers of bins for a few of the quantitative variables. You may find the command `par(mfrow=c(2,2))` useful: it will divide the print window into four regions so that four plots can be made simultaneously. Modifying the arguments to this function will divide the screen in other ways.



    vi. Continue exploring the data, and provide a brief summary of what you discover.



### Exercise 9:

This exercise involves the Auto `data` set studied in the lab. Make sure that the missing values have been removed from the data.

(a) Which of the predictors are quantitative, and which are qualitative?



(b) What is the _range_ of each quantitative predictor? You can answer this using the `range()` function.



(c) What is the mean and standard deviation of each quantitative predictor?



(d) Now remove the 10th through 85th observations. What is the range, mean, and standard deviation of each predictor in the subset of the data that remains?



(e) Using the full data set, investigate the predictors graphically, using scatterplots or other tools of your choice. Create some plots highlighting the relationships among the predictors. Comment on your findings.



(f) Suppose that we wish to predict gas mileage (`mpg`) on the basis
of the other variables. Do your plots suggest that any of the
other variables might be useful in predicting `mpg`? Justify your
answer.


