---
title: "454_Change_Machine"
author: "Michael Gilbert"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  pdf_document: default
  html_document:
    fig_caption: yes
    fig_crop: no
    fig_height: 4.75
    fig_width: 5.75
    highlight: tango
geometry: margin = 0.5in
---
\
```{r setup_knitr, include = F}
knitr::opts_chunk$set(echo = T)
```

# The Change Machine

Write a R function named change.machine() that takes an input value between 0 and 100 and returns a R list object of the number of quarters, dimes, nickels, and pennies required to provide the correct change. If the user inputs a number not in (0,100), then the function should print an error message to the terminal: 'The input value must be between 0 and 100.'. 

```{r Change_Machine}
#==============================================================================
# Function
#==============================================================================
change.machine = function(val){
    val = floor(val + 0.5)
    val.range = seq(0, 100)
    if (!val %in% val.range){
        stop("The input value must be between 0 and 100.")
    }
    q = val %/% 25; q.rem = val %% 25
    d = q.rem %/% 10; d.rem = q.rem %% 10
    n = d.rem %/% 5; n.rem = d.rem %% 5
    p = n.rem %/% 1
    assign("change", list(Quarters = q, Dimes = d, Nickels = n, Pennies = p), 
           envir = .GlobalEnv)
    return(change)
}

#==============================================================================
# Function Call
#==============================================================================
change.machine(88)
```

```{r FIN}
# Session Info
sessionInfo()
```

